-- AlterTable
ALTER TABLE `employeeinfo` MODIFY `department` ENUM('SALES', 'PMR', 'INVENTORY', 'ACCOUNTING', 'IT', 'GENERAL MANAGER', 'DISTRICT MANAGER', 'BUSINESS DEVELOPMENT MANAGER', 'ADMIN') NOT NULL;
